Initial webpack configuration

diff --git a/bin/docker/entrypoint b/bin/docker/entrypoint
--- a/bin/docker/entrypoint
+++ b/bin/docker/entrypoint
@@ -9,6 +9,16 @@ bundle check || {
   }
 }
 
+yarn check || {
+  echo "Installing Yarn packages..."
+  {
+    yarn install >/dev/null 2>&1 && echo "Installed Yarn packages."
+  } || {
+    echo "Yarn installation failed."
+    exit 1
+  }
+}
+
 # remove any old PIDs
 rm -f "tmp/pids/*"
 
